.PHONY: compile
.PHONY: run

compile:
	javac -cp lib/JDA-6.1.2.jar:lib/jl1.0.1.jar:lib/vlcj-4.8.2.jar -d bin src/Main.java src/Bot.java src/TestListener.java src/MP3Player.java



run:
	java -cp "bin:lib/JDA-6.1.2.jar:lib/slf4j-api-1.7.36.jar:lib/slf4j-simple-1.7.36.jar:lib/okhttp-4.9.3.jar:lib/okio-2.8.0.jar:lib/kotlin-stdlib-1.8.0.jar:lib/nv-websocket-client-2.14.jar:lib/trove4j-3.0.3.jar:lib/jackson-core-2.13.5.jar:lib/jackson-annotations-2.13.5.jar:lib/jackson-databind-2.13.5.jar:lib/commons-collections4-4.4.jar:lib/jl1.0.1.jar:lib/vlcj-4.8.2.jar" Main